name: Build TimeChanger APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      
      - name: Create Gradle Wrapper
        run: |
          mkdir -p gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.0.4-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          
      - name: Create Gradle Wrapper Script
        run: |
          echo "#!/usr/bin/env sh" > gradlew
          echo "exec gradle \"\$@\"" >> gradlew
          chmod +x gradlew
        
      - name: Build with Gradle
        run: gradle assembleDebug
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: TimeChanger-debug
          path: app/build/outputs/apk/debug/app-debug.apk 